// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  category: dynamic(() => import("./Category")),
  know_us: dynamic(() => import("./KnowUs")),
  menu_item_with_subitems: dynamic(() => import("./MenuItemWithSubitems")),
  product_carousel: dynamic(() => import("./Product")),
  product_price: dynamic(() => import("./ProductPrice")),
};
